import type { Insight } from '@/content/types';

/** An insight is publishable — and indexable — once it has body paragraphs. */
export const isPublished = (i: Insight): boolean => (i.body?.length ?? 0) > 0;

/** Insights with a written article, for the sitemap. */
export const publishedInsights = (): Insight[] => insights.filter(isPublished);

export const insights: Insight[] = [
  {
    id: 'signals',
    datePublished: '2026-09-12',
    number: '01',
    title: 'Signals before ceremony',
    dek: 'Most UI state does not need a store. Start in the template, promote only what the product actually shares.',
    body: [
      'Every Angular codebase I have inherited has had the same layer in it: a store that exists because the team was told a store was best practice, not because any two parts of the application actually needed to agree on the same value. On the Fiji immigration internal system there were services holding BehaviorSubjects for state that never left the component that created it — a filter panel open/closed flag, the currently expanded row in a table. Each one cost a subscription, an unsubscribe, and a file to open before anyone could understand the template.',
      'The rule I now apply is narrow, and it has held up across immigration case management, a pension member portal and an insurance administration console: state starts in the template, and it is promoted only when a second consumer appears. Not when a second consumer is imagined — when one actually exists in the code. A signal declared next to the markup that reads it is the cheapest thing in Angular to understand, because there is no indirection between the declaration and the use.',
      'Promotion has three steps and I take them in order. First the signal moves from the component to a service, still a signal. Second, if derived values start being recomputed in more than one place, those become computed signals in the same service, so the derivation has exactly one definition. Third — and this is rare — if the state has to survive navigation or be written from unrelated parts of the tree, it earns a store. Most state never reaches step three. On the PRIMS member portal, exactly two pieces of state did: the authenticated member context, and the active claim being edited across a multi-step flow.',
      'The reason the ordering matters is that ceremony is not free, and its cost is paid at the wrong time. A store adds actions, reducers or updaters, selectors, and a mental model that a new developer has to load before they can change a label. That cost is invisible while the team that wrote it is still on the project, and it is the dominant cost afterwards. I have spent more hours tracing a value back through three layers of abstraction to find it was only ever read once than I have spent fixing genuine shared-state bugs.',
      'Signals changed the economics here in a way I think is still underrated. Before signals, keeping state in a component and sharing it later meant a rewrite: template-local fields became observables, templates gained async pipes, and change detection behaviour shifted. The migration was expensive enough that teams pre-emptively started in the store to avoid it. With signals, a component-local signal and a service-level signal are the same primitive — moving one to the other is a cut and a paste. The cost of starting small dropped to nearly zero, which makes starting small the rational default rather than an optimistic one.',
      'Zoneless makes the same point from the other side. Once change detection is driven by signal reads rather than by a zone patching every async API, the framework rewards state that is precisely scoped, because only the components that actually read a signal re-render. Broad, shared, store-held state means broad invalidation. On the Zellavora resume builder, which is zoneless and signal-driven throughout, the components that re-render on a keystroke are the ones displaying the edited field — not because of an optimisation pass, but because that is what the state graph says should happen.',
      'The practical test I give myself before adding a store: can I name the second consumer, and can I point at its file? If the answer is a shape the application might take next quarter, the state stays in the template. It is far easier to promote state that turned out to be shared than to demote state that turned out not to be — the second is a refactor nobody schedules, so it never happens, and the ceremony stays in the codebase for as long as the codebase lives.',
    ],
  },
  {
    id: 'vitals',
    datePublished: '2026-09-12',
    number: '02',
    title: 'Performance is a product requirement',
    dek: 'If Core Web Vitals are optional, they lose. Treat load, input delay and layout shift as part of the spec.',
    body: [
      'The Fiji immigration internal management system ended up roughly 50% faster on the frontend, with about 40% less API consumption. Neither number came from a performance sprint. They came from treating load behaviour as part of the acceptance criteria for the features being built, at the point they were being built, which is the only time the work is cheap.',
      'When performance is a separate phase it competes with features for schedule, and it loses, because a feature has a stakeholder asking for it and a percentage does not. Worse, by the time the phase arrives the causes are structural. A component that fires a request in its constructor is a one-line problem on the day it is written, and an architectural problem six months later when forty components do it and the fix is a caching layer nobody budgeted for.',
      'Most of the API reduction on the immigration system was exactly that class of problem, caught late enough to be real work. Case management screens are dense — a single officer view composed reference data, applicant history, document status and audit trail. Each panel had been built independently, and each fetched what it needed on init. Panels shared reference data heavily, so the same lookup endpoints were being called five and six times per page load. The fix was unglamorous: shared lookups moved behind services that cached for the session, request-level deduplication for the genuinely concurrent cases, and a rule that components receive data as inputs rather than fetching it. The interesting part is that no individual developer did anything wrong. The composition did.',
      'Layout shift has the same shape. It is almost never introduced deliberately; it accumulates from images without dimensions, content that swaps in after a fetch, and banners injected above the fold. Each instance is trivially fixable by the person who wrote it, on the day they wrote it. Collectively they become a score nobody owns. Reserving space is a habit, not a task, and habits are only installable during implementation.',
      'So the spec changes I actually make are small. A ticket that adds a view says what it may fetch on load and what it must receive from its parent. A ticket that adds an image or an embed says the space is reserved. Interaction work states what happens on the input that triggers it — whether the UI acknowledges immediately or waits for the server. These are one-line additions to tickets that were being written anyway, and they move the decision to the only moment when it costs nothing.',
      'Interaction to Next Paint is the metric that has changed my implementation habits most, because it measures something users complained about long before there was a number for it. A button that runs a synchronous filter over a few thousand rows on click feels broken even when the total work is well under a second, and no amount of load-time optimisation compensates. On the insurance administration console the dense table views needed work here specifically: breaking the handler so the interface acknowledges the click in the same frame and does the work after, rather than blocking the main thread and repainting once at the end. Same total work, entirely different product.',
      'None of this requires a performance culture or a dashboard on a wall. It requires performance statements to appear in the same document as functional requirements, so they are reviewed by the same people at the same time. When load, input responsiveness and layout stability sit in the spec, they get built. When they sit in a backlog labelled optimisation, they get discussed.',
    ],
  },
  {
    id: 'quiet-ui',
    datePublished: '2026-09-12',
    number: '03',
    title: 'Quiet interfaces age better',
    dek: 'Motion should explain hierarchy, not decorate it. One accent, one rhythm, and copy that can stand without animation.',
    body: [
      'The interfaces I have built that aged best are the ones where motion explains the structure and then gets out of the way. The ones that aged worst are the ones where the motion was the point. This is not a taste position — it is what I observed going back into these codebases a year later to add features.',
      'Government and pension software makes the argument clearly, because the usage pattern is extreme. An immigration officer works the same case queue for eight hours. A VNPF member opens the app to check a balance and leaves. Neither has any appetite for a transition they have seen four hundred times. Animation that reads as considered on first use reads as latency on the fortieth, and the fortieth use is the one that describes the actual product.',
      'The distinction I hold to is whether the motion is doing work the static layout could not. A panel that slides in from the edge it will return to is telling the user where it came from and how to dismiss it — spatial information the layout cannot express on its own. A card that fades up because cards fade up is decoration. The first survives repetition because it answers a question the user is asking each time; the second only survives novelty.',
      'One accent colour, applied to one job, does more for coherence than any amount of transition polish. Across this portfolio and the client work behind it, the accent marks the thing you can act on next. Not headings, not decoration, not emphasis in running text. When the accent means exactly one thing, a user learns it in a single screen and carries it through the entire product, and every subsequent screen is cheaper to read. The moment it also marks a heading somewhere, it means nothing anywhere.',
      'The same restraint applies to rhythm. A small number of durations and one easing curve, reused everywhere, is perceptible as coherence even though no user could describe it. Every ad-hoc duration is a small inconsistency, and enough of them read as an interface assembled by several people who did not speak — which is usually the literal truth, and exactly what a design system exists to conceal.',
      'The test I use before shipping any animation is to turn it off and read the screen. If the hierarchy collapses, the animation was carrying meaning the layout should have carried, and the layout is the thing to fix. If the screen still reads correctly, the animation is free to stay — it is genuinely additive rather than load-bearing. This matters beyond aesthetics: a meaningful proportion of users have reduced motion enabled, and on this site the motion primitives compile down to plain markup when they do. If the interface only works with motion running, those users get a broken product, and so does anyone on a device slow enough to drop the frames.',
      'The copy has to survive the same test. If a heading only makes sense once the words have staggered into place, it is a heading that depends on a rendering condition — one that fails in a search result, in a screen reader heading list, in an AI-generated summary, and in a browser that decided this frame belonged to something else. Text that stands still is text that works everywhere it gets quoted, which is now most of the places that matter.',
    ],
  },
];
