import type { PricingPlan } from '@/content/types';

export const pricingDisclaimer = 'Pricing shown is indicative and intended to help with initial budgeting. Final pricing depends on scope, complexity, integrations, timeline, design requirements and ongoing support. Domain, hosting, paid APIs, third-party services, licenses and subscriptions are billed separately unless explicitly included in the proposal. International projects available — USD pricing provided during consultation.';

export const pricingPlans: PricingPlan[] = [
  { id: 'project-starter', name: 'Starter', model: 'project', currency: 'INR', startingFrom: '35000', startingLabel: 'Starting from \u20b935,000', scope: 'Individuals, freelancers and small businesses.', timeline: '1-2 weeks', idealClient: 'Personal brands and small sites that need a precise, production-ready frontend.', deliverables: ['Up to 3-5 pages', 'Responsive design', 'Custom UI implementation', 'Angular development', 'Contact form', 'Basic SEO', 'Performance optimization', 'Deployment assistance', '1 revision cycle'] },
  { id: 'project-professional', name: 'Professional', model: 'project', currency: 'INR', startingFrom: '75000', startingLabel: 'Starting from \u20b975,000', featured: true, scope: 'Growing businesses and professional brands.', timeline: '2-4 weeks', idealClient: 'Teams that need Angular 22, signals-based architecture and API integration.', deliverables: ['Up to 6-10 pages', 'Custom UI/UX implementation', 'Angular 22', 'Signals-based architecture', 'Responsive design', 'Advanced animations', 'Contact form', 'API integration', 'SEO optimization', 'Performance optimization', 'Analytics integration', 'Deployment', '2 revision cycles'] },
  { id: 'project-premium', name: 'Premium', model: 'project', currency: 'INR', startingFrom: '150000', startingLabel: 'Starting from \u20b91,50,000', scope: 'Companies, startups and high-impact digital products.', timeline: '4-8+ weeks', idealClient: 'Products that need SSR, accessibility, Playwright testing and a senior architecture pass.', deliverables: ['Custom UX/UI direction', 'Angular 22', 'Signals-first architecture', 'SSR', 'Advanced API integration', 'Authentication where required', 'SEO architecture', 'Performance optimization', 'Accessibility', 'Playwright testing', 'Deployment', 'Technical documentation', '3 revision cycles'] },
  { id: 'retainer-essential', name: 'Essential retainer', model: 'retainer', currency: 'INR', startingFrom: '5000', startingLabel: '\u20b95,000 / month', scope: 'After-launch care for a shipped product.', timeline: 'Month to month', idealClient: 'Owners who need small updates without a new project kickoff.', deliverables: ['Minor updates', 'Dependency updates', 'Basic monitoring', 'Small content changes', 'Bug fixes'] },
  { id: 'retainer-professional', name: 'Professional retainer', model: 'retainer', currency: 'INR', startingFrom: '10000', startingLabel: '\u20b910,000 / month', scope: 'Maintenance plus priority response.', timeline: 'Month to month', idealClient: 'Teams that want a known engineer on call for the frontend.', deliverables: ['Maintenance', 'Performance monitoring', 'Dependency updates', 'Minor feature improvements', 'Technical support', 'Priority response'] },
  { id: 'contract', name: 'Contract / dedicated engineering', model: 'contract', currency: 'INR', startingFrom: null, startingLabel: 'Starting from — Let us discuss', scope: 'Dedicated frontend engineering inside your team.', timeline: 'Scoped per engagement', idealClient: 'Product teams that need a senior Angular / React engineer embedded for a season of work.', deliverables: ['Embedded frontend engineering', 'Architecture and delivery', 'Code reviews', 'Milestone-based timesheets'] },
];

// Re-exported so the contact form and the contact schema share one vocabulary.
export { BUDGET_RANGES as budgetRanges, TIMELINES as timelines } from '@/content/contact-fields';
