import type { ProcessStep } from '@/content/types';

export const processIntro = {
  index: '06',
  label: 'My Process',
  headingLines: ['From Problem', 'to Production.'],
  lede: "I don't start with code. I start by understanding the problem, the people using the product, and what success needs to look like — then I turn that understanding into a clear, maintainable path from idea to production.",
  ctaHeading: 'Have a product in mind?',
  ctaLede: "Let's turn the problem into something people can actually use.",
} as const;

export const processPrinciples = [
  {
    title: 'Clear communication',
    body: 'Important decisions are made visible early instead of becoming surprises during development.',
  },
  {
    title: 'Small, reviewable iterations',
    body: 'I prefer working in manageable increments so progress can be reviewed before large amounts of work are committed.',
  },
  {
    title: 'Engineering with context',
    body: "I don't choose a technology simply because it is popular. The technical approach should fit the product, users, constraints, and long-term maintenance needs.",
  },
  {
    title: 'Quality throughout the process',
    body: "Testing, accessibility, responsiveness, and performance aren't activities reserved for the final day. They are considered throughout delivery.",
  },
  {
    title: 'Build for the next release',
    body: "I aim to solve today's problem without creating tomorrow's maintenance problem.",
  },
] as const;

export const processSteps: ProcessStep[] = [
  {
    id: 'discover',
    number: '01',
    label: 'Discover',
    title: 'Understand the problem before solving it',
    purpose: 'Understand the business goal, users, constraints and workflows.',
    description:
      'Every strong product starts with clarity. I begin by understanding the business goal, users, existing workflows, technical constraints, and what is actually causing the problem.',
    happens: [
      'Understand the product and business context',
      'Identify primary users and workflows',
      'Review existing applications and systems',
      'Understand technical constraints',
      'Identify risks and dependencies',
      'Clarify project goals and priorities',
      'Define what success should look like',
    ],
    deliverables: [
      'Project context',
      'User/workflow understanding',
      'Initial scope',
      'Key assumptions',
      'Technical considerations',
      'Success criteria',
    ],
    output: 'Research notes · Initial scope · Success criteria',
    outcome: 'A shared understanding of what we are actually trying to solve.',
    visual: 'discover',
  },
  {
    id: 'define',
    number: '02',
    label: 'Define',
    title: 'Turn ambiguity into a buildable plan',
    purpose: 'Translate requirements into structured delivery plans.',
    description:
      "Once the problem is clear, I translate it into structured requirements and a practical delivery plan. The goal isn't to document everything for the sake of documentation. The goal is to remove uncertainty before it becomes expensive rework.",
    happens: [
      'Break requirements into clear capabilities',
      'Define user journeys',
      'Identify functional requirements',
      'Identify non-functional requirements',
      'Prioritize features',
      'Identify edge cases',
      'Define technical constraints',
      'Map dependencies',
      'Establish delivery milestones',
    ],
    deliverables: [
      'Feature scope',
      'User flows',
      'Requirements',
      'Acceptance criteria',
      'Technical assumptions',
      'Delivery roadmap',
    ],
    output: 'Feature scope · Delivery roadmap · Technical assumptions',
    outcome: 'Everyone knows what needs to be built, why it matters, and what "done" means.',
    visual: 'define',
  },
  {
    id: 'design',
    number: '03',
    label: 'Design',
    title: 'Design the experience before building the interface',
    purpose: 'Shape user journeys and reusable UI patterns.',
    description:
      'Good engineering starts with good decisions. I translate requirements into intuitive user experiences and scalable interface structures before implementation begins.',
    happens: [
      'Map important user journeys',
      'Define information architecture',
      'Create wireframes where required',
      'Design responsive layouts',
      'Establish reusable UI patterns',
      'Define component states',
      'Consider loading and error states',
      'Consider accessibility from the beginning',
      'Validate complex workflows',
    ],
    deliverables: [
      'User flows',
      'Wireframes',
      'UI direction',
      'Responsive layouts',
      'Component patterns',
      'Interaction states',
    ],
    output: 'UI direction · Reusable patterns · Responsive layouts',
    outcome: 'A clear interface direction that engineering can build confidently.',
    visual: 'design',
  },
  {
    id: 'build',
    number: '04',
    label: 'Engineer',
    title: 'Turn the design into a production-ready product',
    purpose: 'Build modular, frontend systems with maintainable code.',
    description:
      'This is where ideas become software. I build modular frontend systems with a strong focus on maintainability, performance, scalability, and real-world user experience.',
    happens: [
      'Build reusable components',
      'Implement responsive interfaces',
      'Integrate APIs',
      'Manage application state',
      'Implement forms and validation',
      'Handle loading and error states',
      'Build authentication flows',
      'Optimize rendering',
      'Implement accessibility',
      'Write maintainable TypeScript',
      'Integrate backend services',
      'Maintain clean project architecture',
    ],
    deliverables: [
      'Reusable components',
      'Responsive interfaces',
      'API integration',
      'State management',
      'Form validation',
      'Accessible UI',
    ],
    output: 'Type-safe code · Component library · Integrated APIs',
    outcome: 'A working product built for real users — not just a working prototype.',
    visual: 'build',
  },
  {
    id: 'test',
    number: '05',
    label: 'Validate',
    title: 'Make sure it works beyond the happy path',
    purpose: 'Validate functionality, responsiveness, accessibility, and performance.',
    description:
      "A feature isn't finished because it works once. I validate functionality, responsiveness, accessibility, performance, and edge cases before release.",
    happens: [
      'Validate functional behaviour',
      'Form validation',
      'API responses',
      'Error handling',
      'Browser compatibility',
      'Responsive layouts',
      'Mobile behaviour',
      'Accessibility',
      'Performance',
      'Loading states',
      'Empty states',
      'Edge cases',
    ],
    deliverables: [
      'Unit testing',
      'Integration testing',
      'End-to-end testing',
      'Browser testing',
      'Responsive testing',
      'Manual QA',
      'Performance validation',
    ],
    output: 'Playwright E2E · Unit/Integration tests · Accessibility audits',
    outcome: 'Confidence before production.',
    visual: 'test',
  },
  {
    id: 'launch',
    number: '06',
    label: 'Launch',
    title: 'Move from tested software to production',
    purpose: 'Configure and deploy for real-world usage.',
    description:
      'A successful launch is more than pushing code. I make sure the application is configured correctly and ready for real-world usage.',
    happens: [
      'Prepare production configuration',
      'Verify environment variables',
      'Build production assets',
      'Configure deployment',
      'Validate production APIs',
      'Check routes',
      'Verify SEO',
      'Validate analytics',
      'Monitor initial behaviour',
      'Resolve launch issues',
    ],
    deliverables: [
      'CI/CD setup',
      'Environment separation',
      'Staged releases',
      'Production monitoring',
      'Rollback strategy',
      'Performance monitoring',
    ],
    output: 'Deployment pipeline · Production config · Monitoring stack',
    outcome: 'A stable production release that is ready for users.',
    visual: 'launch',
  },
  {
    id: 'evolve',
    number: '07',
    label: 'Evolve',
    title: 'Launch is not the end of the product',
    purpose: 'Improve continuously based on real feedback.',
    description:
      'Real products change. Users provide feedback, requirements evolve, performance can be improved, and new business needs appear. I treat production as the beginning of the next improvement cycle.',
    happens: [
      'Monitor production issues',
      'Review user feedback',
      'Fix defects',
      'Improve performance',
      'Refine UX',
      'Maintain dependencies',
      'Improve accessibility',
      'Add new capabilities',
      'Refactor technical debt',
      'Support future releases',
    ],
    deliverables: [
      'Issue monitoring',
      'Performance tuning',
      'UX refinement',
      'Dependency maintenance',
      'Feature additions',
    ],
    output: 'Refined UX · Dependency upgrades · Iterative releases',
    outcome: 'A product that continues to become more useful, reliable, and maintainable.',
    visual: 'evolve',
  },
];
