import type { ServiceOffering } from "@/content/types";

/** The eight cards in the services grid, in display order. */
export const serviceOfferings: ServiceOffering[] = [
  {
    id: "frontend",
    number: "01",
    title: "Frontend Development",
    description: "Building fast, responsive, and accessible web applications with Angular.",
    stack: ["Angular", "TypeScript", "RxJS"],
    icon: "code",
    href: "/services/web-application-development",
  },
  {
    id: "fullstack",
    number: "02",
    title: "Full-Stack Development",
    description: "End-to-end solutions using modern stacks, APIs, and scalable architectures.",
    stack: ["Node.js", "Express", "PostgreSQL"],
    icon: "layers",
    href: "/services",
  },
  {
    id: "mobile",
    number: "03",
    title: "Mobile App Development",
    description: "Cross-platform mobile apps with Ionic & Capacitor for seamless experiences.",
    stack: ["Ionic", "Capacitor", "PWA"],
    icon: "phone",
    href: "/services/mobile-app-development",
  },
  {
    id: "cloud",
    number: "04",
    title: "Cloud & DevOps Solutions",
    description: "CI/CD pipelines, cloud deployment, and infrastructure to ship faster and scale effortlessly.",
    stack: ["Docker", "CI/CD", "Vercel"],
    icon: "cloud",
    href: "/services",
  },
  {
    id: "design",
    number: "05",
    title: "UI/UX Design & Prototyping",
    description: "Designing intuitive, modern, and user-focused interfaces that drive engagement.",
    stack: ["Figma", "UI/UX", "Prototyping"],
    icon: "pen",
    href: "/services",
  },
  {
    id: "backend",
    number: "06",
    title: "Backend & API Development",
    description: "Robust RESTful APIs and backend systems built for performance and reliability.",
    stack: ["NestJS", "Prisma", "REST APIs"],
    icon: "server",
    href: "/services",
  },
  {
    id: "performance",
    number: "07",
    title: "Performance & Optimization",
    description: "Optimizing web apps for speed, SEO, and Core Web Vitals excellence.",
    stack: ["SEO", "SSR", "Core Web Vitals"],
    icon: "shield",
    href: "/services",
  },
  {
    id: "support",
    number: "08",
    title: "Maintenance & Support",
    description: "Ongoing support, feature updates, and performance monitoring to keep your product ahead.",
    stack: ["Support", "Monitoring", "Updates"],
    icon: "support",
    href: "/services",
  },
];
